RATE_PER_MINUTE: float = 10.0
WINDOW_SECONDS: float = 300.0
DURATION_SECONDS: float = 600.0
MAX_WORKERS: int = 10

FILE_COUNT: int = 100
BUCKET_SIZE_MB: float = 10.0
MEAN_FILE_SIZE_MB: float = 2.0

TOURNAMENT_PLAYERS: int = 12
TOURNAMENT_TABLES: int = 3
TOURNAMENT_GROUP_SIZE: int = 4
TOURNAMENT_ROUNDS: int = 5
